#!/bin/sh

# Check if there are changes in the 'data' directory after a pull
changed_files=$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)
data_directory_changed=$(echo "$changed_files" | grep "^data/")

if [ -n "$data_directory_changed" ]; then
    python3 when_changed.py
fi
